name: Release Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release:
    env:
      DATA: nuller
      VERSION: nuller
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    
    - name: Leer Archivo XML
      run: |
        version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        # Imprimir la versión
        echo "La versión del artefacto es: $version"
        echo "VERSION=$version" >> $env:GITHUB_ENV
    - name: Check for Release
      run: |
        VERSION=${{ env.VERSION }}
        if [ ! -z "$VERSION" ]; then
          if ! git rev-list "$VERSION" &>/dev/null; then
            YEAR_MONTH=$(date +'%Y%m')
            echo $YEAR_MONTH
            echo "DATA=$YEAR_MONTH" >> $env:GITHUB_ENV
            echo "VERSION=$VERSION" >> $env:GITHUB_ENV
          else
            echo "Release $VERSION already exists."
          fi
        else
          echo "No version found in pom.xml."
        fi
    - name: create release
      if: ${{ env.DATA != 'nuller' && env.VERSION != 'nuller' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.DATA }}
        name: ${{ env.VERSION }}
        body: hello
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
